version: '3.9'
services:
  blog-database:
    image: mongo
    ports:
      - '27017:27017'

  blog-backend:
    build: backend/
    env_file:
      - backend/.env
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb://blog-database:27017/blog
    ports:
      - '3001:3001'
    depends_on:
      - blog-database

  blog-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: http://blog-backend:3001/api/v1
        VITE_GRAPHQL_URL: http://blog-backend:3001/graphql
    environment:
      - PORT=3000
      - SSR_BACKEND_URL=http://blog-backend:3001/api/v1
      - VITE_BACKEND_URL=http://blog-backend:3001/api/v1
      - VITE_GRAPHQL_URL=http://blog-backend:3001/graphql
    ports:
      - '3000:3000'
    depends_on:
      - blog-backend
